#! /bin/sh
tmux kill-session -t comma
cd /data/openpilot/selfdrive/car/modules/radarFlasher
cp /data/openpilot/selfdrive/ui/qt/flasher ./flasher
exec ./flasher "VIN Lrn" vin_learn.sh "-" vin_learn.sh info.sh
