Import('env', 'arch', 'is_tbp', 'messaging', 'common', 'visionipc')

src = ['loggerd.cc', 'logger.cc']
libs = ['zmq', 'czmq', 'capnp', 'kj', 'z',
  'avformat', 'avcodec', 'swscale', 'avutil',
  'yuv', 'bz2', common, 'json', messaging, visionipc]

if arch == "aarch64":
  if not is_tbp:
    src += ['encoder.c', 'raw_logger.cc']
    libs += ['OmxVenc', 'OmxCore', 'cutils']

env.Program(src, LIBS=libs)
