Import('env', 'arch','is_tbp', 'common', 'messaging', 'gpucommon', 'visionipc', 'cereal')

src = ['ui.cc', 'paint.cc', 'sidebar.cc', '#phonelibs/nanovg/nanovg.c']
libs = [common, 'zmq', 'czmq', 'capnp', 'capnp_c', 'm', cereal, messaging, gpucommon, visionipc]

if is_tbp:
  arch = "aarch64_TBP"
if arch == "aarch64":
  src += ['sound.cc', 'slplay.c']
  libs += ['EGL', 'GLESv3', 'gnustl_shared', 'log', 'utils', 'gui', 'hardware', 'ui', 'CB', 'gsl', 'adreno_utils', 'OpenSLES', 'cutils', 'uuid', 'OpenCL']
  linkflags = ['-Wl,-rpath=/system/lib64,-rpath=/system/comma/usr/lib']
else:
  src += ['linux.cc']
  libs += ['pthread', 'glfw']
  linkflags = []

env.Program('_ui', src,
  LINKFLAGS=linkflags,
  LIBS=libs)
